# Generated by Django 5.2.14 on 2026-05-10 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("pending_approval", "Pending Approval"),
                    ("active", "Active"),
                    ("rejected", "Rejected"),
                    ("suspended", "Suspended"),
                ],
                default="draft",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("active", "Active"),
                    ("disabled", "Disabled"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
