# Generated by Django 5.2.14 on 2026-05-26 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_organization_status_alter_membership_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("coworking_space", "Co-working Space"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
