# Generated by Django 5.2.14 on 2026-05-27 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("level_number", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="floors",
                        to="offices.office",
                    ),
                ),
            ],
            options={
                "ordering": ["level_number", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("office", "slug"), name="unique_floor_slug_per_office"
                    ),
                    models.UniqueConstraint(
                        fields=("office", "level_number"),
                        name="unique_floor_level_per_office",
                    ),
                ],
            },
        ),
    ]
