# Generated by Django 5.2.14 on 2026-05-30 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0002_floor"),
    ]

    operations = [
        migrations.CreateModel(
            name="FloorLayoutObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[
                            ("desk", "Desk"),
                            ("standing_desk", "Standing Desk"),
                            ("hot_desk", "Hot Desk"),
                            ("private_desk", "Private Desk"),
                            ("chair", "Chair"),
                            ("office_chair", "Office Chair"),
                            ("meeting_chair", "Meeting Chair"),
                            ("lounge_chair", "Lounge Chair"),
                            ("bench", "Bench"),
                            ("sofa", "Sofa"),
                            ("table", "Table"),
                            ("lunch_table", "Lunch Table"),
                            ("boardroom_table", "Boardroom Table"),
                            ("coffee_table", "Coffee Table"),
                            ("room", "Room"),
                            ("meeting_room", "Meeting Room"),
                            ("quiet_room", "Quiet Room"),
                            ("focus_zone", "Focus Zone"),
                            ("phone_booth", "Phone Booth"),
                            ("meeting_pod", "Meeting Pod"),
                            ("wall", "Wall"),
                            ("door", "Door"),
                            ("window", "Window"),
                            ("column", "Column"),
                            ("partition", "Partition"),
                            ("toilet", "Toilet"),
                            ("sink", "Sink"),
                            ("kitchen_sink", "Kitchen Sink"),
                            ("cabinet", "Cabinet"),
                            ("locker", "Locker"),
                            ("printer", "Printer"),
                            ("tv", "TV"),
                            ("whiteboard", "Whiteboard"),
                            ("plant", "Plant"),
                            ("label", "Label"),
                            ("shape", "Shape"),
                        ],
                        max_length=40,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=120)),
                ("x", models.DecimalField(decimal_places=2, max_digits=10)),
                ("y", models.DecimalField(decimal_places=2, max_digits=10)),
                ("width", models.DecimalField(decimal_places=2, max_digits=10)),
                ("height", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "rotation",
                    models.DecimalField(decimal_places=2, default=0, max_digits=6),
                ),
                ("is_bookable", models.BooleanField(default=False)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layout_objects",
                        to="offices.floor",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(fields=["floor"], name="layout_obj_floor_idx"),
                    models.Index(
                        fields=["floor", "object_type"],
                        name="layout_obj_floor_type_idx",
                    ),
                    models.Index(
                        fields=["floor", "is_active"],
                        name="layout_obj_floor_active_idx",
                    ),
                ],
            },
        ),
    ]
