# Generated by Django 5.2.14 on 2026-05-30 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_other_org_type"),
        ("offices", "0003_floorlayoutobject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Desk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("code", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desks",
                        to="offices.floor",
                    ),
                ),
                (
                    "layout_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desks",
                        to="offices.floorlayoutobject",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desks",
                        to="offices.office",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desks",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["organization", "is_active"], name="desk_org_active_idx"
                    ),
                    models.Index(
                        fields=["office", "is_active"], name="desk_office_active_idx"
                    ),
                    models.Index(
                        fields=["floor", "is_active"], name="desk_floor_active_idx"
                    ),
                    models.Index(fields=["status"], name="desk_status_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("layout_object",),
                        name="unique_active_desk_per_layout_object",
                    )
                ],
            },
        ),
    ]
