# Generated by Django 5.2.14 on 2026-05-31 08:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_other_org_type"),
        ("offices", "0004_desk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeskBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "desk",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="offices.desk",
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desk_bookings",
                        to="offices.floor",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desk_bookings",
                        to="offices.office",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desk_bookings",
                        to="accounts.organization",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="desk_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["organization", "booking_date", "status"],
                        name="db_org_date_status_idx",
                    ),
                    models.Index(
                        fields=["office", "booking_date", "status"],
                        name="db_ofc_date_status_idx",
                    ),
                    models.Index(
                        fields=["floor", "booking_date", "status"],
                        name="db_flr_date_status_idx",
                    ),
                    models.Index(
                        fields=["desk", "booking_date", "status"],
                        name="db_dsk_date_status_idx",
                    ),
                    models.Index(
                        fields=["user", "booking_date", "status"],
                        name="db_usr_date_status_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("desk", "booking_date"),
                        name="unique_active_booking_per_desk_date",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "active")),
                        fields=("organization", "user", "booking_date"),
                        name="unique_active_booking_per_user_org_date",
                    ),
                ],
            },
        ),
    ]
