# Generated by Django 5.2.14 on 2026-05-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_other_org_type"),
        ("offices", "0005_add_desk_booking_model"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="desk",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("is_active", True), models.Q(("code", ""), _negated=True)
                ),
                fields=("office", "code"),
                name="unique_active_desk_code_per_office",
            ),
        ),
    ]
