# Generated by Django 5.2.14 on 2026-06-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0006_add_unique_active_desk_code_per_office"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="deskbooking",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="desk_bookings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
