# Generated by Django 5.2.14 on 2026-06-18 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0007_set_null_deskbooking_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="boundary_height",
            field=models.DecimalField(
                decimal_places=2,
                default=544,
                max_digits=7,
                validators=[
                    django.core.validators.MinValueValidator(240),
                    django.core.validators.MaxValueValidator(4000),
                ],
            ),
        ),
        migrations.AddField(
            model_name="floor",
            name="boundary_width",
            field=models.DecimalField(
                decimal_places=2,
                default=904,
                max_digits=7,
                validators=[
                    django.core.validators.MinValueValidator(240),
                    django.core.validators.MaxValueValidator(4000),
                ],
            ),
        ),
    ]
