# Generated by Django 5.2.14 on 2026-06-22 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offices", "0010_enhancerun_enhancerunoperation"),
    ]

    operations = [
        migrations.AddField(
            model_name="floor",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")],
                default="published",
                max_length=20,
            ),
        ),
    ]
