# Generated by Django 5.2.14 on 2026-06-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("offices", "0011_floor_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="floorlayoutobject",
            name="object_type",
            field=models.CharField(
                choices=[
                    ("desk", "Desk"),
                    ("standing_desk", "Standing Desk"),
                    ("hot_desk", "Hot Desk"),
                    ("private_desk", "Private Desk"),
                    ("chair", "Chair"),
                    ("office_chair", "Office Chair"),
                    ("meeting_chair", "Meeting Chair"),
                    ("lounge_chair", "Lounge Chair"),
                    ("bench", "Bench"),
                    ("sofa", "Sofa"),
                    ("chair_table_set", "Chair & Table Set"),
                    ("stool", "Stool"),
                    ("table", "Table"),
                    ("lunch_table", "Lunch Table"),
                    ("boardroom_table", "Boardroom Table"),
                    ("coffee_table", "Coffee Table"),
                    ("room", "Room"),
                    ("lobby", "Lobby"),
                    ("kitchen", "Kitchen"),
                    ("bathroom", "Bathroom"),
                    ("meeting_room", "Meeting Room"),
                    ("quiet_room", "Quiet Room"),
                    ("focus_zone", "Focus Zone"),
                    ("phone_booth", "Phone Booth"),
                    ("meeting_pod", "Meeting Pod"),
                    ("wall", "Wall"),
                    ("door", "Door"),
                    ("window", "Window"),
                    ("column", "Column"),
                    ("partition", "Partition"),
                    ("cutout", "Cutout"),
                    ("toilet", "Toilet"),
                    ("sink", "Sink"),
                    ("kitchen_sink", "Kitchen Sink"),
                    ("cabinet", "Cabinet"),
                    ("locker", "Locker"),
                    ("printer", "Printer"),
                    ("tv", "TV"),
                    ("whiteboard", "Whiteboard"),
                    ("plant", "Plant"),
                    ("label", "Label"),
                    ("shape", "Shape"),
                ],
                max_length=40,
            ),
        ),
    ]
