# Generated by Django 5.2.14 on 2026-07-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0012_alter_floorlayoutobject_object_type"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="floorlayoutobject",
            name="layout_obj_floor_idx",
        ),
        migrations.AddConstraint(
            model_name="floorlayoutobject",
            constraint=models.CheckConstraint(
                condition=models.Q(("width__gt", 0), ("height__gt", 0)),
                name="layout_obj_positive_size",
            ),
        ),
    ]
