# Generated by Django 5.2.14 on 2026-07-14 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0013_remove_floorlayoutobject_layout_obj_floor_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enhancerun",
            name="status",
            field=models.CharField(
                choices=[
                    ("success", "Success"),
                    ("partial_success", "Partial success"),
                    ("failed", "Failed"),
                    ("skipped", "Skipped"),
                ],
                max_length=20,
            ),
        ),
    ]
