# Generated by Django 5.2.14 on 2026-07-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("offices", "0014_alter_enhancerun_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="floorlayoutobject",
            name="is_bookable",
        ),
    ]
