# Generated by Django 5.2.14 on 2026-08-08 22:32

import django.contrib.postgres.constraints
import django.core.validators
import django.db.models.deletion
import offices.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_other_org_type"),
        ("offices", "0016_btree_gist_extension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MeetingRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("unavailable", "Unavailable"),
                            ("maintenance", "Maintenance"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("amenities", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_rooms",
                        to="offices.floor",
                    ),
                ),
                (
                    "layout_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_rooms",
                        to="offices.floorlayoutobject",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_rooms",
                        to="offices.office",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="meeting_rooms",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RoomBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("booking_date", models.DateField()),
                ("start_at", models.DateTimeField()),
                ("end_at", models.DateTimeField()),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("cancelled", "Cancelled")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cancelled_room_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "floor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to="offices.floor",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to="offices.office",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_bookings",
                        to="accounts.organization",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="bookings",
                        to="offices.meetingroom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="room_bookings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-booking_date", "start_at"],
            },
        ),
        migrations.AddIndex(
            model_name="meetingroom",
            index=models.Index(
                fields=["office", "is_active"], name="room_office_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingroom",
            index=models.Index(
                fields=["floor", "is_active"], name="room_floor_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="meetingroom",
            index=models.Index(fields=["status"], name="room_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="meetingroom",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("layout_object",),
                name="unique_active_room_per_layout_object",
            ),
        ),
        migrations.AddIndex(
            model_name="roombooking",
            index=models.Index(
                fields=["organization", "booking_date", "status"],
                name="rb_org_date_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roombooking",
            index=models.Index(
                fields=["floor", "booking_date", "status"],
                name="rb_flr_date_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roombooking",
            index=models.Index(
                fields=["room", "booking_date", "status"],
                name="rb_room_date_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="roombooking",
            index=models.Index(
                fields=["user", "booking_date", "status"], name="rb_usr_date_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="roombooking",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_at__gt", models.F("start_at"))),
                name="room_booking_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="roombooking",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                condition=models.Q(("status", "active")),
                expressions=[
                    ("room", "="),
                    (
                        offices.models.TsTzRange(
                            "start_at", "end_at", models.Value("[)")
                        ),
                        "&&",
                    ),
                ],
                name="room_booking_no_overlap",
            ),
        ),
    ]
