# Generated by Django 5.2.14 on 2026-08-09 10:47

import django.db.models.deletion
import users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatConfirmToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("book_desk", "Book desk"),
                            ("cancel_desk", "Cancel desk booking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payload", models.JSONField(default=dict)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_confirm_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
            bases=(users.models.ExpiringTokenMixin, models.Model),
        ),
        migrations.CreateModel(
            name="ProcessedChatEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(choices=[("slack", "Slack")], max_length=20),
                ),
                ("event_id", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["created_at"], name="chatevent_created_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "event_id"),
                        name="unique_processed_chat_event",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="BotActionAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(choices=[("slack", "Slack")], max_length=20),
                ),
                ("external_user_id", models.CharField(max_length=255)),
                ("command", models.CharField(max_length=40)),
                ("args", models.JSONField(blank=True, default=dict)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("ok", "OK"),
                            ("error", "Error"),
                            ("already_handled", "Already handled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bot_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"], name="botaudit_user_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ChatLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(choices=[("slack", "Slack")], max_length=20),
                ),
                ("external_user_id", models.CharField(max_length=255)),
                ("external_team_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("linked", "Linked"),
                            ("revoked", "Revoked"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                ("linked_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chat_links",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["platform", "external_user_id"],
                        name="chatlink_identity_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "external_user_id"),
                        name="unique_chat_identity",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "linked")),
                        fields=("platform", "external_user_id"),
                        name="unique_linked_chat_identity",
                    ),
                ],
            },
            bases=(users.models.ExpiringTokenMixin, models.Model),
        ),
    ]
