# Generated by Django 5.2.14 on 2026-08-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="botactionaudit",
            name="platform",
            field=models.CharField(
                choices=[("slack", "Slack"), ("teams", "Teams")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="chatlink",
            name="platform",
            field=models.CharField(
                choices=[("slack", "Slack"), ("teams", "Teams")], max_length=20
            ),
        ),
        migrations.AlterField(
            model_name="processedchatevent",
            name="platform",
            field=models.CharField(
                choices=[("slack", "Slack"), ("teams", "Teams")], max_length=20
            ),
        ),
    ]
