# Generated by Django 5.2.14 on 2026-08-16 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_mfaloginchallenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar_url",
            field=models.URLField(blank=True, default="", max_length=1024),
        ),
    ]
